#!/usr/bin/env ruby

require 'Kobold'
require 'tty-option'
require 'pry'

module Kobold
  class Command
    include TTY::Option

    usage do
      program "kobold"

      commands "init", "invoke"

    end

    argument :command do
      optional
      desc "Accepts commands for Kobold to execute."
    end

    flag :help do
      short "-h"
      long "--help"
      desc "Print usage."
    end

    def run
      if params[:help]
        print help
      elsif params.errors.any?
        puts params.errors.summary
      else
        #pp params.to_h
      end
    end
  end
end


cmd = Kobold::Command.new
parse = cmd.parse
run = cmd.run

if cmd.params[:command] == nil || cmd.params == "invoke"
  Kobold.invoke
else
  case cmd.params[:command]
  when "add"
  when "remove"
  when "update"
  when "list"
    Kobold.list
  when "init"
    Kobold.init
  else
    print cmd.help
  end
end
